// line 2 - 5 creates global variables being called throughout the javascript
var free_flight_tally = 2; // Tally of how many free flights are left, called in prize
var top_number = 50; // sets the top number in the prize genertator
var low_prize_items = ['prize 1', 'prize 2', 'prize 3']; // array of prize to be called in prize()
var money_prize_items = ['10', '20', '100']; // array of prize to be called in prize()


/*Function myMove is called by the spin button in the html, is used to create the
 angle of the moose needs to spin and calls the emailformdisplay.
*/
function myMove() {

  var elem = document.getElementById("myAnimation"); // variable to create a link to the animation in the html

 // calculates the angle by first making it do 2 full turns and then pick a random number between 0-1
  var angle = 720 +  Math.floor((Math.random() * 100) + 1);

    //bring together the element id in the html and adds the styling of rotation using the random number generated by angle varable
   elem.style.transform = 'rotate('+ angle + 'deg)';
   // adds a duration to the rotation on the selected id from the html
	 elem.style.transitionDuration = "2s";

   //creates a break between the mosse spinning and calling the emailformdisplay from appearing
	 setTimeout(emailformdisplay, 3000);
    }

//function is called by myMove after the spinning has finished and waited for 3 seconds
	function emailformdisplay (){
    //Creates the link to a new id element in the html which is the contact form
       var form = document.getElementById('ContactInfo');
        var game = document.getElementById('game');
          var button = document.getElementById('button');
        // calles the id element in the html and removes display none from the css
          form.style.display = "block";
          game.style.display = "none";
          button.style.display = "none";
    }



/*function pize is only called once the user has entered in their contact details, this will make sure that the tally of the
prize are not effected by user who do not want to sign up */
function prize (){
  var prize = document.getElementById("prize"); // creates the link to html element where the prize will be shown
  var prize_number = 31; // geneates a random prize number by calling the global variable top_number

  //follwing statments are used to work out which prize the user has won

  /* The first if statment is used to find out if they have won the top prize, if they
  have it will take the global varable top_number and take one away, this make sure that
  the top number can only be one once in a life time. After this it send back a message to html
  telling the user what they have won*/
  if(prize_number == 50){
    top_number = top_number - 1;
    prizeDisplay ();
    prize.innerHTML= 'You have won a all exspense trip';
	  }
    /*The second statment works out if they have won the second top prize by checking if the prize number
    between 45 and 49. As well make sure free flight tally is greater then 2, to make sure it is only won twice
    this is done by pulling down the flight free_flight_tally. If the prize is won it takes away one from the global tally
    and pass back the prize message*/
    else if((prize_number >= 45) && (prize_number <= 49) && (free_flight_tally > 0)){
      free_flight_tally = free_flight_tally - 1;
        prizeDisplay ();
      prize.innerHTML = 'You have free flights';
    }
    /*The third statment check to see if the user has won one of the money prize,
    by checking to see if the prize_number between 31 and 44. If it is a random
    prize is selected from the money_prize array, by calculating the length of the array
    and selecting one at random. Then money_prize_items is passed back to the prize message
    to be display in the html.
    */
    else if((prize_number >= 31) && (prize_number <= 44)){
      money_prize = money_prize_items[Math.floor(Math.random()*money_prize_items.length)];
      prizeDisplay ();
      prize.innerHTML = 'You have won ' +'\xA3' + money_prize;
    }


    /*The fourth statment check to see if the user has won one of the money prize,
    by checking to see if the prize_number between 0 and 30. If it is a random
    prize is selected from the low_prize_items array, by calculating the length of the array
    and selecting one at random. Then low_prize_items is passed back to the prize message
    to be display in the html.
    */
    else if ((prize_number >= 0) && (prize_number <= 30)){
      low_prize = low_prize_items[Math.floor(Math.random()*low_prize_items.length)];
      prizeDisplay ();
      prize.innerHTML = low_prize;
    }
    /* The final else is used to call the function again, this will only be reached if
    free_flight_tally has reached 0*/
    else{
      prize();
    }
  }



function prizeDisplay (){

    //Creates the link to a new id element in the html which is the contact form
       var form = document.getElementById('ContactInfo');
        var game = document.getElementById('game');
          var button = document.getElementById('button');
        // calles the id element in the html and removes display none from the css
          form.style.display = "none";
          game.style.display = "block";
          button.style.display = "none";

}
